### ISSUE TITLE
“Attempting to change value of a readonly property” in createPropType.js

### ISSUE THREAD

**Issue by ixje** [benwiley4000/react-extra-prop-types#1]
The following line throws the error in the subject on Adroid (with react-native).
`Object.defineProperty(propType, 'name', { value: type });`

Note that that line does not cause any issues on iOS. I [resolved it](https://github.com/ixje/react-extra-prop-types/commit/62f8a27e1d2ed815b3fffff4d155bc25f1b7f18d) by using assignment instead of definition. I'm aware there are some differences for mutability and for prototype, but for this lib I'm not really worried about that. The test-cases all pass with this simple fix. 

I currently don't know of a better way to fix this quickly, but I leave that up to you to decide if this is an acceptable solution. I can PR if you want (after removing the commented line).

**Comment by benwiley4000** [comment]
Could I see the error log you're getting?

I think your solution is fine and I'll take a PR, but I'd just like to check out the error first. 🙂

**Comment by benwiley4000** [comment]
Sorry, I'm slow - just saw the error message in the title of the issue. 😛

Seems really odd that the code would error in that way - especially since writing the property the other way **does** work. You would think that if `name` were already read-only, it wouldn't work to say `propType.name = blah`.

Anyway, please feel free to make a PR, but could we maybe do a try/catch - e.g.
```js
try {
  Object.defineProperty(/*...*/);
} catch (e) {
  // link to issue thread on github
  propType.name = /*...*/;
}
```

**Comment by ixje** [comment]
No worries, I'll try the try-catch tomorrow when i'm home to see if that also solves it. If so i can pr with that.

**Comment by benwiley4000** [comment]
I'm now remembering why this line exists in the first place - `propType.name = 'foobar'` is never going to error, but it just won't do anything if the function is already named. `Object.defineProperty` works in most cases.

Setting the `name` property on the function is for debugging purposes - it's nonessential. If a platform isn't going to support renaming a function, we should just skip it rather than trying to do `propType.name = 'foobar'` instead - I don't think that would actually achieve the desired behavior.

However do me a favor and check on android what the result of `console.log(propType.name)` is after your new line. If it actually changes the value, the direct assignment is an acceptable fallback. Otherwise we should just leave a comment and do nothing.

**Comment by ixje** [comment]
As per your request: 
console.log(propType.name) -> 'propType'

I've changed the code to use a try-catch + linking to this issue. PR incoming.
